baseurl = "/"
title = "Computer Vision Talks"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
disqusShortname = "cvtalks" # Enable comments by entering your Disqus shortname
googleAnalytics = "UA-10687369-5" # Enable Google Analytics by entering your tracking id

[Author]
    name = "Eugene Khvedchenya"
    bio = "Eugene Khvedchenya is a computer vision developer skilled in high-performance image processing. In his spare time he loves to share his knowledge and thoughts about computer vision and augmented reality"
    avatar = "img/avatar.png"


[Params]
    subtitle = "All you want to know about image processing" # Subtitle of your site
    description = "A personal blog about computer vision, AI, machine learning and programmin in OpenCV" # Description of your site
    opengraph = true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = true
    post_navigation = true


[Params.widgets]
    search = true # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget 
    categories = true # Enable "Categories" widget
    tags = true # Enable "Tags" widget